### ISSUE TITLE
9.5.7制裁的可以看看是不是因为自动更新了

### ISSUE THREAD

**Issue by iiSlash** [hyue418/taobao-11-11#124]
我昨晚还用的957满奖励 今天发现变100 200 一看版本更新到了9.15.7 重新下9.5.7之后用脚本还是满奖励

**Comment by zycboss** [comment]
同9.5.7，今天跑完一遍没有发现被制裁，当时降完级就赶紧把应用商店里淘宝的自动更新关了，就是为了防止这种事情的发生

**Comment by maltsugar** [comment]
应该不是自动更新  我压根没开过自动更新， 应用商店里也永久忽略

**Comment by koen100** [comment]
不太确定是不是自动更新,我是今天跑了20w金币以后被黑,发现被黑以后立马卸载换8.11,仍然是黑号

**Comment by lv100** [comment]
没有唉 还是9.5.7   继续跑慎重吧

**Comment by zhugexiaoshang** [comment]
Thank you for your letter！  I've received your letter, I'll reply to you as soon as possible.
