### ISSUE TITLE
实测退回8.11版本后正常了

### ISSUE THREAD

**Issue by lujc** [hyue418/taobao-11-11#135]
MIUI 12，把读取软件列表（不让App知道我有auto.js）和写盘权限全部关闭（防止热更新）。退回8.11版，除了登录会跳出强更新提示外，其它一切正常了。淘宝太坑了，白白损失了2天的喵币。

**Comment by youaaaaa** [comment]
实测MIUI12 :  关闭 ''读取应用权限'' 和 ''写盘权限''  并关闭 "无障碍" 和 "autojs"          在8.11版本手动操作+200;

而使用最新某宝;  关闭 ''无障碍'' ;   手动操作+20000;

是否该账号被记录 只要在非最新版某宝登录一律奖励变成1%

**Comment by lujc** [comment]
> 实测MIUI12 : 关闭 ''读取应用权限'' 和 ''写盘权限'' 并关闭 "无障碍" 和 "autojs" 在8.11版本手动操作+200;
> 
> 而使用最新某宝; 关闭 ''无障碍'' ; 手动操作+20000;
> 
> 是否该账号被记录 只要在非最新版某宝登录一律奖励变成1%

之前最新版的手淘App中，手动刷也只能奖励+100（现在8.11可以用auto.js），搞不懂其惩罚机制

**Comment by JunShine** [comment]
同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了

**Comment by youaaaaa** [comment]
> 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了

我也是ios全黑,只能手动正常,   但是我autojs是为了蚂蚁能量,  所以不卸载,还好关无障碍可以手动

**Comment by JunShine** [comment]
> > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> 
> 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动

还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。

**Comment by llllcccjjj** [comment]
我的miui一直跑一点问题都没

**Comment by lujc** [comment]
> > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> 
> 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动

所有电商平台，淘宝的活动搞最复杂，最耗时间精力，到手的钱还不多，现在还封脚本，所以我宁可少点钱，也不愿意手动刷任务，不然这个付出和收获太不成正比了

**Comment by youaaaaa** [comment]
> > > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> > 
> > 
> > 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动
> 
> 还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。

京东有个大能出了pc版   强的一批

**Comment by JunShine** [comment]
> > > > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> > > 
> > > 
> > > 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动
> > 
> > 
> > 还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。
> 
> 京东有个大能出了pc版 强的一批

哪个？关键词透露一下？

**Comment by youaaaaa** [comment]
> > > > > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> > > > 
> > > > 
> > > > 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动
> > > 
> > > 
> > > 还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。
> > 
> > 
> > 京东有个大能出了pc版 强的一批
> 
> 哪个？关键词透露一下？

52那边

**Comment by koen100** [comment]
实测,卸载autojs的情况下,9.15最新版手动可以正常拿金币.  降版本到9.5.7变黑号

**Comment by biggest-cai** [comment]
> > > > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> > > 
> > > 
> > > 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动
> > 
> > 
> > 还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。
> 
> 京东有个大能出了pc版 强的一批

直接上链接吧

**Comment by JunShine** [comment]
我觉得还是自己动手找找好，免得像autojs这样了

**Comment by hnliuzesen** [comment]
> > > > > 同MIUI12，已被封的一个号只能卸载旧版本，清除数据后，安装最新版本手动执行才正常，但是使用IOS依然黑号。没被封的号冒险试了一下9.5.7和8.11开脚本还能正常，IOS也没问题。怕了，卸载脚本全手动算了，就怕某天黑了回不来就闹心了
> > > > 
> > > > 
> > > > 我也是ios全黑,只能手动正常, 但是我autojs是为了蚂蚁能量, 所以不卸载,还好关无障碍可以手动
> > > 
> > > 
> > > 还可以刷京东^_^，我刚刚装回去了哈哈哈。淘宝只能手动算了。
> > 
> > 
> > 京东有个大能出了pc版 强的一批
> 
> 哪个？关键词透露一下？

兜兜风

**Comment by wongweihin** [comment]
> 实测MIUI12 : 关闭 ''读取应用权限'' 和 ''写盘权限'' 并关闭 "无障碍" 和 "autojs" 在8.11版本手动操作+200;
> 
> 而使用最新某宝; 关闭 ''无障碍'' ; 手动操作+20000;
> 
> 是否该账号被记录 只要在非最新版某宝登录一律奖励变成1%

同MIUI12，在Android端黑号，实测IOS端同样黑，推论是已经在服务器端被标记。而且标记黑号直接用就版本就惩罚，最后更潜在秋后清算的可能（例如：红包的派发上克扣，最终人均能拿到20，被黑号后只能拿几元）
【纯好奇】在禁止读取应用列表 及 剪切板的情况下，脚本的滑动据说已经在坐标及滑动距离、间隔时间上做了随机数（没仔细看代码），手淘APP是如何检测到脚本模拟操作的...

**Comment by koen100** [comment]
如果是在服务器端被标记的话,那安卓端应该也是黑号的,我用安卓正常,ios黑号

**Comment by JunShine** [comment]
> > 实测MIUI12 : 关闭 ''读取应用权限'' 和 ''写盘权限'' 并关闭 "无障碍" 和 "autojs" 在8.11版本手动操作+200;
> > 而使用最新某宝; 关闭 ''无障碍'' ; 手动操作+20000;
> > 是否该账号被记录 只要在非最新版某宝登录一律奖励变成1%
> 
> 同MIUI12，在Android端黑号，实测IOS端同样黑，推论是已经在服务器端被标记。而且标记黑号直接用就版本就惩罚，最后更潜在秋后清算的可能（例如：红包的派发上克扣，最终人均能拿到20，被黑号后只能拿几元）
> 【纯好奇】在禁止读取应用列表 及 剪切板的情况下，脚本的滑动据说已经在坐标及滑动距离、间隔时间上做了随机数（没仔细看代码），手淘APP是如何检测到脚本模拟操作的...

检测无障碍？

**Comment by koen100** [comment]
实测ios降版本到9.11还是黑号

**Comment by hidetag** [comment]
实测：
8.11 淘宝 + 卸载 AutoJs + 手动做任务 = 200
9.5 淘宝 + 卸载 AutoJs + 手动做任务 = 200 
最新版淘宝（清除数据，adb uninstall com.taobao.taobao） + 卸载 AutoJs（adb uninstall org.autojs.autojspro） + 手动做任务  = 全金币

**Comment by hidetag** [comment]
> 实测：
> 8.11 淘宝 + 卸载 AutoJs + 手动做任务 = 200
> 9.5 淘宝 + 卸载 AutoJs + 手动做任务 = 200
> 最新版淘宝（清除数据，adb uninstall com.taobao.taobao） + 卸载 AutoJs（adb uninstall org.autojs.autojspro） + 手动做任务 = 全金币

Android，MIUI 12

**Comment by lujc** [comment]
> > > 实测MIUI12 : 关闭 ''读取应用权限'' 和 ''写盘权限'' 并关闭 "无障碍" 和 "autojs" 在8.11版本手动操作+200;
> > > 而使用最新某宝; 关闭 ''无障碍'' ; 手动操作+20000;
> > > 是否该账号被记录 只要在非最新版某宝登录一律奖励变成1%
> > 
> > 
> > 同MIUI12，在Android端黑号，实测IOS端同样黑，推论是已经在服务器端被标记。而且标记黑号直接用就版本就惩罚，最后更潜在秋后清算的可能（例如：红包的派发上克扣，最终人均能拿到20，被黑号后只能拿几元）
> > 【纯好奇】在禁止读取应用列表 及 剪切板的情况下，脚本的滑动据说已经在坐标及滑动距离、间隔时间上做了随机数（没仔细看代码），手淘APP是如何检测到脚本模拟操作的...
> 
> 检测无障碍？

如果在MIUI中的权限把
