### ISSUE TITLE
建议：设置淘宝-获取应用列表权限为关闭

### ISSUE THREAD

**Issue by wangp-blog** [hyue418/taobao-11-11#142]
淘宝会在脚本执行过程中自动获取应用权限，建议关闭

**Comment by wongweihin** [comment]
自安装后都手动关了，不起任何作用的...可以确定的是，黑号不是靠这个来检测的。

**Comment by TEENSTITANS** [comment]
淘宝APP安卓版 8.11.0，关闭应用权限，刚刚测试100%奖励。

**Comment by czs85149451** [comment]
我9.0一点问题都没有

**Comment by koen100** [comment]
卸载autojs的情况下,只要使用低版本就黑号,用最新就可正常领. ios则是完全黑号

**Comment by ali5199** [comment]
> 卸载autojs的情况下,只要使用低版本就黑号,用最新就可正常领. ios则是完全黑号

确实如此。
