### ISSUE TITLE
SyntaxError: invalid object initializer (<淘宝双11超级星秀猫脚本>#352)

### ISSUE THREAD

**Issue by weijhao** [hyue418/taobao-11-11#25]
你们用的是啥手机啊，
我华为p20 emui9.1
小米k30 miui12.0.9
tb9.5.7
AUTO 4.0.1 beta
运行都是11:51:39.961/E: SyntaxError: invalid object initializer (<淘宝双11超级星秀猫脚本>#352)

**Comment by hyue418** [comment]
> 你们用的是啥手机啊，
> 我华为p20 emui9.1
> 小米k30 miui12.0.9
> tb9.5.7
> AUTO 4.0.1 beta
> 运行都是11:51:39.961/E: SyntaxError: invalid object initializer (<淘宝双11超级星秀猫脚本>#352)

开启无障碍并授权给Auto.js

**Comment by yyt64949** [comment]
这东西咱下载啊

**Comment by Dacanid** [comment]
> > 你们用的是啥手机啊，
> > 我华为p20 emui9.1
> > 小米k30 miui12.0.9
> > tb9.5.7
> > AUTO 4.0.1 beta
> > 运行都是11:51:39.961/E: SyntaxError: invalid object initializer (<淘宝双11超级星秀猫脚本>#352)
> 
> 开启无障碍并授权给Auto.js

均已授权
![image](https://user-images.githubusercontent.com/17106493/97101359-acee2500-16d7-11eb-8192-e59dd303bb8e.png)
以上为小米
![image](https://user-images.githubusercontent.com/17106493/97101367-bd060480-16d7-11eb-96d6-d9325d90b541.png)
以上为华为

**Comment by weijhao** [comment]
> > 你们用的是啥手机啊，
> > 我华为p20 emui9.1
> > 小米k30 miui12.0.9
> > tb9.5.7
> > AUTO 4.0.1 beta
> > 运行都是11:51:39.961/E: SyntaxError: invalid object initializer (<淘宝双11超级星秀猫脚本>#352)
> 
> 开启无障碍并授权给Auto.js

均已授权
![image](https://user-images.githubusercontent.com/70306815/97101385-fc345580-16d7-11eb-953d-43603d6192b3.png)
以上为小米
![image](https://user-images.githubusercontent.com/70306815/97101387-048c9080-16d8-11eb-8ce4-84862fd951da.png)
以上为华为

**Comment by weijhao** [comment]
安装auto.js-4.1.0就好了，是软件版本问题
