### ISSUE TITLE
崩溃日志，大佬解惑。我打开autojs的悬浮窗老提示我没赋权，其实已经允许了

### ISSUE THREAD

**Issue by cagen056** [hyue418/taobao-11-11#65]
Version: 452
Android: 29
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1468)
com.stardust.autojs.core.ui.dialog.BlockedMaterialDialog.show(BlockedMaterialDialog.java:42)
com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1457)
com.stardust.autojs.core.ui.dialog.BlockedMaterialDialog$Builder.access$001(BlockedMaterialDialog.java:58)
com.stardust.autojs.core.ui.dialog.BlockedMaterialDialog$Builder.lambda$showAndGet$12(BlockedMaterialDialog.java:169)
com.stardust.autojs.core.ui.dialog.-$$Lambda$BlockedMaterialDialog$Builder$vpJElWWLrXD-z4TgINikfWMsS28.run(Unknown Source:2)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:7562)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by SusonJohn** [comment]
先关app再开启权限，再运行，可能你的app仍有后台运行导致权限信息没有同步

**Comment by cagen056** [comment]
> 先关app再开启权限，再运行，可能你的app仍有后台运行导致权限信息没有同步

OK，这样的确崩溃减少了。
