### ISSUE TITLE
请问大佬跳转到淘宝猫猫活动的隐示意图是怎么获得的呢？

### ISSUE THREAD

**Issue by zhsh2980** [hyue418/taobao-11-11#7]
我看到跳转到活动的地址是 taobao://pages.tmall.com/wow/z/hdwk/act-20201111/index

想知道跳转到超级红包的地址是什么，请指教，谢谢~

**Comment by hyue418** [comment]
> 我看到跳转到活动的地址是 taobao://pages.tmall.com/wow/z/hdwk/act-20201111/index
> 
> 想知道跳转到超级红包的地址是什么，请指教，谢谢~

APP里面嵌入了H5页，然后H5页上有个分享按钮，点复制链接里面就会有H5页的URL出来了
这个是比较便捷的方法，否则就要拿安卓root之后开代理抓包了

**Comment by zhsh2980** [comment]
多谢，明白了

**Comment by a997449595** [comment]
请问大佬taobao://pages.tmall.com/wow/z/hdwk/act-20201111/index 这个页面链接是怎么获取的

**Comment by hyue418** [comment]
> 请问大佬taobao://pages.tmall.com/wow/z/hdwk/act-20201111/index 这个页面链接是怎么获取的

看下上边回复的内容
