### ISSUE TITLE
防封思路以及TB今天的新防脚本

### ISSUE THREAD

**Issue by ohhhyy** [hyue418/taobao-11-11#89]
不知道为什么我的号总是走在被检测的最前沿，最开始换9.5版本也无法防止黑号，然后用thanox把淘宝的“可读取已安装程序列表”权限禁掉，就这么用了一段时间作者的脚本。
前天又发现200金币黑号现象。干脆换了9.0版本，同样禁止TB读取已安装程序，又这么正常了两天直到今天，在做任务的时候，明明已经完成了任务，任务列表里就是不显示已完成（就是那个已完成的按钮永远是去浏览），必须退出任务列表再进入才能正常显示，就造成脚本一直在做已完成的任务。不知道我是个例还是有别人跟我同样情况？
16年的老号了，就今年薅点羊毛就这么难，心累想退休

**Comment by wudixiaoqiang** [comment]
你没怀疑过是手机的事？换个手机

**Comment by CL545740896** [comment]
手机设备号 GG了~ 换个手机吧

**Comment by SusonJohn** [comment]
重新打开就好了，其实这种也不算完全是检测机制，有可能只是他一个简单的缓存机制，关脚本，清理一下重新走一次就好，最后等他几分钟，这样缓存清理更优

**Comment by ohhhyy** [comment]
忘记补充 我的设备和ROM：小米5+魔趣，小米6+lineage，一加8p+miui12。淘宝版本均已降级为9.0
换设备后能正常一两个任务，然后就重复我上面的情况。。。楼上朋友说的清理缓存也清理了，重新安装淘宝都是清理缓存+数据
心累想退休

**Comment by ohhhyy** [comment]
又测试了一遍 是我的问题
9.0关闭获取已安装列表权限就会出现以上情况，不关闭一切恢复正常。
9.5.7未测试，正常使用的不要关闭获取已安装列表权限。

**Comment by SusonJohn** [comment]
> 又测试了一遍 是我的问题
> 9.0关闭获取已安装列表权限就会出现以上情况，不关闭一切恢复正常。
> 9.5.7未测试，正常使用的不要关闭获取已安装列表权限。

建议9.5.7不要试，先聚集在9.0，毕竟sdk可能比较旧，热推也推不到多少补丁。
还有就是权限加一个小米的虚拟那种，或者开询问就可以了，直接禁用的话，一般来说是直接被ban，因为有些参数拿不到，是一个好明显的作法，估计在接口传参上做了处理的

**Comment by ohhhyy** [comment]
9.0失效，退回8.11.0
发现JD比TB活动力度大而且没有检测，弃坑TB了
